### ISSUE TITLE
jackdmp-1.9.11

### ISSUE THREAD

**Issue by madorian** [njh/jackminimix#1]
On my Ubuntu-16.10, there's jackdmp-1.9.11. 

Does there exist a jackminimixer package for ubuntu or can I compile it against jackdmp?

**Comment by njh** [comment]
I believe jackdmp has exactly the same API at the original implementation of jackd, so yes, it should compile fine.

I have not made a jackminimix packagemyself, but it is possible that someone else has.

**Comment by njh** [comment]
No response, so closing.
