### ISSUE TITLE
How can I receive return values from OSC server?

### ISSUE THREAD

**Issue by crocket** [njh/jackminimix#6]
`oscsend` from liblo and python-osc cannot retreive return values from the OSC server in jackminimix.

Am I missing something?

**Comment by crocket** [comment]
https://github.com/attwad/python-osc/issues/104 closes this issue.

**Comment by njh** [comment]
Making requests and then receiving a response is a bit icky with OSC. Unfortunately there isn't really a good way of doing it.

See this code for how I did it with perl:
https://github.com/njh/jackminimix/blob/master/perl/lib/Audio/JackMiniMix.pm

(you basically have to run a little local 'server' on your client, that binds to the same port and handles a callback with the response in it).

I hope you manage to get it working with Python.

**Comment by crocket** [comment]
The way I did it is

```
>>> import pythonosc.udp_client as uc
>>> client=uc.SimpleUDPClient("localhost", 14629)
>>> client.send(uc.OscMessageBuilder("/mixer/get_channel_count").build())
>>> res=uc.OscMessage(client._sock.recv(4096))
>>> res.address
'/mixer/channel_count'
>>> res.params
[1]
```

I did so because I didn't know how to extract port number from a python UDP socket.

**Comment by crocket** [comment]
Does jackminimix accumulate unhandled return values in UDP socket if OSC clients don't retrieve return values?

I'm starting to think that JSON TCP/UDP API is going to be easier.

**Comment by njh** [comment]
No. UDP is fire and forget. Your python script will have the packets sitting in its buffer, or if they fail to be received, then they will just disappear.

I think if I was to re-write JackMiniMix, then I would use MQTT.

**Comment by crocket** [comment]
Does MQTT make it easy to retrieve return values?

**Comment by crocket** [comment]
I think MQTT is better.
